test: job wordflow2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,28 +61,30 @@ jobs:
 
   test-needs-build:
     runs-on: ubuntu-latest
-
     steps:
       - name: Test
-        run: echo "test job executed"
-
+        run: |
+          echo "This job will fail"
+          exit 1
 
   test-deploy-staging:
     needs: test-needs-build
     runs-on: ubuntu-latest
-
     steps:
-      - name: Staging
-        run: echo "staging job executed"
-
+      - run: echo "Staging"
 
   test-deploy-production:
     needs: test-deploy-staging
     runs-on: ubuntu-latest
-
     steps:
-      - name: Production
-        run: echo "production job executed"
+      - run: echo "Production"
+
+  test-notification:
+    needs: test-needs-build
+    if: failure()
+    runs-on: ubuntu-latest
+    steps:
+      - run: echo "Build failed! Send notification here."
 
   deploy-staging:
     needs: build
